#! /bin/zsh

setopt ALL_EXPORT
typeset -xU path PATH
# editor
EDITOR=nvim
VISUAL=nvim

PASSWORD_STORE_GPG_OPTS="--homedir /Users/bruce.wang/.pass_gpg"
GPG_TTY=$(tty)

# aws cli
AWS_DEFAULT_REGION=us-west-2
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_REGION=ap-southeast-2

# TERM
TERM=${TERM:-xterm-256color}

JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8-openj9.jdk/Contents/Home

# node
NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules:$HOME/.config/yarn/global/node_modules

path=($HOME/bin $HOME/.local/bin /opt/homebrew/bin /opt/homebrew/sbin $HOME/.cargo/bin $HOME/.config/yarn/global/node_modules/.bin  $JAVA_HOME/bin /usr/local/lib/ruby/gems/2.5.0/bin /usr/local/bin $GOPATH/bin $path)

path=(
    # allow directories only (-/)
    # reject world-writable directories (^W)
    ${^path}(N-/^W)
)

export PATH
unsetopt ALL_EXPORT
# vi:ft=zsh
