#! /bin/zsh

setopt ALL_EXPORT
typeset -xU path PATH 
# editor
EDITOR=nvim
VISUAL=nvim

# password_store
PASSWORD_STORE_GPG_OPTS="--homedir /Users/bruce.wang/.pass_gpg"
PASSWORD_STORE_DEFAULT_SEPARATOR=","
PASSWORD_STORE_WORD_COUNT="4"
PASSWORD_STORE_ENABLE_EXTENSIONS=true

# GPG_TTY=$(tty)

# aws cli
AWS_DEFAULT_REGION=us-west-2
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_REGION=us-west-2

# TERM
TERM=${TERM:-xterm-256color}

# node
NODE_PATH=$HOME/.config/yarn/global/node_modules

path=(
  /opt/homebrew/opt/coreutils/libexec/gnubin
  $HOME/.local/share/nvim/mason/bin
  $HOME/.asdf/bin
  $HOME/.arkade/bin/
  $HOME/.rd/bin
  $HOME/bin
  $HOME/.local/bin
  $HOME/go/bin
  $HOME/.cargo/bin
  $HOME/.config/yarn/global/node_modules/.bin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  $path
)

path=(
    # allow directories only (-/)
    # reject world-writable directories (^W)
    ${^path}(N-/^W)
)

export PATH
unsetopt ALL_EXPORT
# vi:ft=zsh
