#! /bin/zsh

setopt ALL_EXPORT
# editor
EDITOR=vim
VISUAL=vim


# TERM
TERM=${TERM:-xterm-256color}

# node
NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

path+=($HOME/bin /usr/local/sbin /usr/local/bin $PATH)


# aws cli
AWS_DEFAULT_REGION=ap-southeast-2

# Golang
GOPATH=/Users/bruce/go
path+=($GOPATH/bin)

export PATH
unsetopt ALL_EXPORT
# vi:ft=zsh
