#!/usr/bin/env zsh

zmodload zsh/terminfo
bindkey -v
bindkey  "${terminfo[home]}"    beginning-of-line
bindkey  "${terminfo[kend]}"     end-of-line
bindkey  "${terminfo[kich1]}"    overwrite-mode
bindkey  "${terminfo[kdch1]}"    delete-char
bindkey  "${terminfo[cuu1]}"    history-substring-search-up
bindkey  "${terminfo[kcud1]}"    history-substring-search-down
bindkey  "${terminfo[kcub1]}"    backward-char
bindkey  "${terminfo[kcuf1]}"   forward-char


# vim: ft=zsh
