#! /bin/zsh

setopt ALL_EXPORT
typeset -xU path PATH 
# editor
EDITOR=vim
VISUAL=vim

# aws cli
AWS_DEFAULT_REGION=ap-southeast-2

# TERM
TERM=${TERM:-xterm-256color}

# node
NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

# Golang
GOPATH=/Users/bruce/go
path=($HOME/bin /usr/local/sbin /usr/local/bin $GOPATH/bin $path)

path=(
    # allow directories only (-/)
    # reject world-writable directories (^W)
    ${^path}(N-/^W)
)

export PATH
unsetopt ALL_EXPORT
# vi:ft=zsh
