#! /bin/zsh

setopt ALL_EXPORT
typeset -xU path PATH 
# editor
EDITOR=vi
VISUAL=vi

GOPASS_GPG_OPTS='--homedir /Users/bruce/.pass_gpg'
GPG_TTY=$(tty)

# aws cli
AWS_DEFAULT_REGION=us-west-2

# TERM
TERM=${TERM:-xterm-256color}

# node
NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules:$HOME/.config/yarn/global/node_modules

path=($HOME/bin $HOME/.config/yarn/global/node_modules/.bin /usr/local/lib/ruby/gems/2.5.0/bin /usr/local/bin $GOPATH/bin $HOME/.krew/bin $path)

path=(
    # allow directories only (-/)
    # reject world-writable directories (^W)
    ${^path}(N-/^W)
)

export PATH
unsetopt ALL_EXPORT
# vi:ft=zsh
